# Northflank Environment Variables and Secrets Configuration
# Copy this file and fill in your actual API keys and configuration values

apiVersion: v1
kind: Secret
metadata:
  name: short-video-maker-secrets
type: Opaque
data:
  # Base64 encoded secrets - use: echo -n "your-api-key" | base64
  PEXELS_API_KEY: ""  # Your Pexels API key
  ELEVENLABS_API_KEY: ""  # ElevenLabs API key for TTS
  OPENAI_API_KEY: ""  # OpenAI API key
  AZURE_SPEECH_KEY: ""  # Azure Speech Service key
  AZURE_SPEECH_ENDPOINT: ""  # Azure Speech endpoint
  AZURE_SPEECH_REGION: ""  # Azure region (e.g., eastus)
  GOOGLE_TTS_API_KEY: ""  # Google Cloud TTS API key
  GOOGLE_CLOUD_PROJECT: ""  # Google Cloud project ID
  KOKORO_API_KEY: ""  # Kokoro TTS API key

---
# Environment Variables Configuration
environment:
  # TTS Configuration
  TTS_DEFAULT_PROVIDER: "elevenlabs"  # or "kokoro", "azure", "google"
  TTS_MAX_BUDGET: "100"
  TTS_MAX_CHARACTERS: "1000000"
  TTS_ENABLE_COST_OPTIMIZATION: "true"
  TTS_ENABLE_HEALTH_MONITORING: "true"
  TTS_MAX_REQUESTS_PER_MINUTE: "60"
  TTS_MAX_CONCURRENT_REQUESTS: "5"
  TTS_REQUEST_TIMEOUT_MS: "30000"
  TTS_RETRY_ATTEMPTS: "3"

  # Application Configuration
  PORT: "8080"
  LOG_LEVEL: "info"
  ENABLE_TTS_DEBUG: "false"
  
  # Docker/Container Configuration
  DATA_DIR_PATH: "/app/data"
  DOCKER: "true"
  CONCURRENCY: "1"
  VIDEO_CACHE_SIZE_IN_BYTES: "2097152000"  # 2GB

  # CUDA Performance Settings
  CUDA_VISIBLE_DEVICES: "0"
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"
  CUDA_MODULE_LOADING: "LAZY"
  TORCH_CUDNN_V8_API_ENABLED: "1"
  CUDNN_BENCHMARK: "1"
  
  # PyTorch Memory Management
  PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:512,garbage_collection_threshold:0.8,expandable_segments:True"
  TORCH_CUDA_ARCH_LIST: "7.5;8.0;8.6;8.9;9.0"
  
  # FramePack GPU Optimizations
  FRAMEPACK_GPU_MEMORY_FRACTION: "0.85"
  FRAMEPACK_USE_TENSORRT: "true"
  FRAMEPACK_ENABLE_MEMORY_POOLING: "true"
  FRAMEPACK_BATCH_SIZE_AUTO: "true"
  
  # Whisper CUDA Optimizations
  WHISPER_CUDA_BATCH_SIZE: "16"
  WHISPER_CUDA_ENABLE_FLASH_ATTENTION: "1"

  # Redis Configuration (if external Redis)
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  # REDIS_PASSWORD: ""  # Uncomment if Redis has password

# Instructions:
# 1. Fill in all API keys and secrets
# 2. Encode secrets in base64: echo -n "your-secret" | base64
# 3. Create secrets in Northflank dashboard
# 4. Set environment variables in deployment configuration
# 5. Adjust resource limits based on your needs